name: dart_obfuscator
description: A command line tool that obsfucate dart code that can be 
distribued as a package. 
version: 0.0.1
homepage:
repository: https://github.com/BankingofThings/dart-obfuscator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.3

dev_dependencies:
  test: ^1.15.4
